export type ReservationEmailData = {
  reservationId: string;
  customerName?: string | null;
  customerEmail?: string | null;
  reservedDate?: string | null;
  startAt?: string | null;
  endAt?: string | null;
  packageLabel?: string | null;
  cabinCode?: string | null;
  totalAmount?: number | string | null;
  depositAmount?: number | string | null;
  paymentMethod?: string | null;
  paymentUrl?: string | null;
  clientUrl?: string | null;
  adminUrl?: string | null;
  status?: string | null;
  note?: string | null;
  amount?: number | string | null;
  reason?: string | null;
};
